[package]
name = "fortune-cookie"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
hyper = {version = "*", default-features = false}
regex = "*"

[features]
default = ["ssl"]
ssl = ["hyper/ssl"]
